"""add images table 2

Revision ID: 366e7899ee6c
Revises: b64c4be6f990
Create Date: 2025-12-31 00:09:16.993827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "366e7899ee6c"
down_revision: Union[str, Sequence[str], None] = "b64c4be6f990"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "hotel_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column("hotel_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
