"""add booking2

Revision ID: bc086075b8c0
Revises: 0cc9d5c7188f
Create Date: 2025-11-07 12:30:07.899988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc086075b8c0"
down_revision: Union[str, Sequence[str], None] = "0cc9d5c7188f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking", sa.Column("date_from", sa.Date(), nullable=False))
    op.add_column("booking", sa.Column("date_to", sa.Date(), nullable=False))
    op.drop_column("booking", "data_from")
    op.drop_column("booking", "data_to")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "booking", sa.Column("data_to", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "booking",
        sa.Column("data_from", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_column("booking", "date_to")
    op.drop_column("booking", "date_from")
    # ### end Alembic commands ###
