"""add images table 3

Revision ID: 7a2d6e44a063
Revises: 366e7899ee6c
Create Date: 2025-12-31 01:39:19.486840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7a2d6e44a063"
down_revision: Union[str, Sequence[str], None] = "366e7899ee6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("image_bites", sa.LargeBinary(), nullable=False))
    op.drop_column("images", "image_binary")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column(
            "image_binary", postgresql.BYTEA(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("images", "image_bites")
    # ### end Alembic commands ###
