"""добавил relationship в модели image и hotel

Revision ID: 53dc190f60db
Revises: cc23c5c309f4
Create Date: 2026-01-30 18:42:43.132841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53dc190f60db"
down_revision: Union[str, Sequence[str], None] = "cc23c5c309f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
