"""ограничение для price и quantity >0 для rooms1

Revision ID: e187157594a8
Revises: 48bd5e370e53
Create Date: 2026-01-29 17:36:20.171145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e187157594a8"
down_revision: Union[str, Sequence[str], None] = "48bd5e370e53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
