"""cascade для удобств

Revision ID: e3690a1aa04c
Revises: e187157594a8
Create Date: 2026-01-29 22:15:45.128784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3690a1aa04c"
down_revision: Union[str, Sequence[str], None] = "e187157594a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("rooms_facilities_facility_id_fkey"),
        "rooms_facilities",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("rooms_facilities_room_id_fkey"), "rooms_facilities", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "rooms_facilities",
        "facilities",
        ["facility_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "rooms_facilities", "rooms", ["room_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rooms_facilities", type_="foreignkey")
    op.drop_constraint(None, "rooms_facilities", type_="foreignkey")
    op.create_foreign_key(
        op.f("rooms_facilities_room_id_fkey"),
        "rooms_facilities",
        "rooms",
        ["room_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("rooms_facilities_facility_id_fkey"),
        "rooms_facilities",
        "facilities",
        ["facility_id"],
        ["id"],
    )
    # ### end Alembic commands ###
