"""уникальный адрес для каждого отеля

Revision ID: 74b56f8577bc
Revises: 1eb7f9fb78ba
Create Date: 2026-01-29 15:04:33.998994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74b56f8577bc"
down_revision: Union[str, Sequence[str], None] = "1eb7f9fb78ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "hotels", ["location"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hotels", type_="unique")
    # ### end Alembic commands ###
