"""теперь при удалении отеля, удаляется и изображение

Revision ID: 70412a340c8c
Revises: 716edba1ff9f
Create Date: 2026-01-30 18:07:47.937179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70412a340c8c"
down_revision: Union[str, Sequence[str], None] = "716edba1ff9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("hotels_images_hotel_id_fkey"), "hotels_images", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("hotels_images_image_id_fkey"), "hotels_images", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "hotels_images", "hotels", ["hotel_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "hotels_images", "images", ["image_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hotels_images", type_="foreignkey")
    op.drop_constraint(None, "hotels_images", type_="foreignkey")
    op.create_foreign_key(
        op.f("hotels_images_image_id_fkey"),
        "hotels_images",
        "images",
        ["image_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("hotels_images_hotel_id_fkey"),
        "hotels_images",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    # ### end Alembic commands ###
