"""change images_id to image_id

Revision ID: 29d233730afe
Revises: 7a2d6e44a063
Create Date: 2026-01-03 14:33:36.621934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29d233730afe"
down_revision: Union[str, Sequence[str], None] = "7a2d6e44a063"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hotels_images", sa.Column("image_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("hotels_images_images_id_fkey"), "hotels_images", type_="foreignkey"
    )
    op.create_foreign_key(None, "hotels_images", "images", ["image_id"], ["id"])
    op.drop_column("hotels_images", "images_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotels_images",
        sa.Column("images_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "hotels_images", type_="foreignkey")
    op.create_foreign_key(
        op.f("hotels_images_images_id_fkey"),
        "hotels_images",
        "images",
        ["images_id"],
        ["id"],
    )
    op.drop_column("hotels_images", "image_id")
    # ### end Alembic commands ###
