"""добавил relationship в модели image и hotel1

Revision ID: b3c04bbb7c3c
Revises: 53dc190f60db
Create Date: 2026-01-30 18:53:34.077630

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3c04bbb7c3c"
down_revision: Union[str, Sequence[str], None] = "53dc190f60db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
