"""ограничение для price и quantity >0 для rooms

Revision ID: 48bd5e370e53
Revises: cca5f08691b3
Create Date: 2026-01-29 17:26:59.870119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48bd5e370e53"
down_revision: Union[str, Sequence[str], None] = "cca5f08691b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
